### ISSUE TITLE
Traje + Dash = matar enemigo

### ISSUE THREAD

**Issue by ClaudiaZarzuela** [Proyectos1-FDI-UCM/c2022-Grupo05#10]
### Descripción
Cuando el jugador hace uso del traje mejorado y a la misma vez usa el Dash para chocarse contra un enemigo, le mata por completo. En el informe pone que se le debería quitar un punto de vida al enemigo, no matarlo de una.

### Pasos 
Para poder recrear ese error se debe:
Paso 1: pulsar la ‘q’ para hacer uso del traje mejorado.
Paso 2: usar el dash contra un enemigo.

### Captura de pantalla o vídeo
https://drive.google.com/file/d/1g6khC-d-EQzSyJPH_27Q69tyQUo7qJMZ/view?usp=sharing

**Comment by NanxiQin** [comment]
Ya está arreglado en la nueva versión
