### ISSUE TITLE
El disparo colisiona con el jugador

### ISSUE THREAD

**Issue by pablosm196** [Proyectos1-FDI-UCM/c2022-Grupo05#2]
##Nombre del error (frase breve descriptiva)
El disparo colisiona con el jugador.
##Descripción
El proyectil colisiona con las piernas del jugador, cuando no debería interaccionar con el jugador
##Pasos
Detallar los pasos seguidos para poder reproducir el error. Si no se ha podido reproducir, entonces indicarlo igualmente.
1.	Saltar
2.	Disparar antes de completar el salto
3.	Dash en la dirección del disparo
##Captura de pantalla o vídeo
https://drive.google.com/file/d/1pox5JlfRVpGuebuPemfFLAq9B1ABcM4d/view?usp=sharing

**Comment by Santienper** [comment]
El error ha sido resuelto.
