### ISSUE TITLE
vueltas indefinidas (gravitación)

### ISSUE THREAD

**Issue by efeliua** [Proyectos1-FDI-UCM/c2022-Grupo05#3]
##Nombre del error: 
Vueltas indefinidas
##Descripción: 
El jugador se queda girando de forma ininterrumpida en el aire. Puede desplazarse de derecha a izquierda mientras gira pero no saltar ni cambiar definitivamente de gravitación. Tampoco puede usar el dash o powerups.
##Pasos:
Al intentar cambiar de gravitación en un espacio determinado, cogiendo una moneda y saltando a la vez. Desconozco el origen exacto del fallo. 
##Vídeo con el error:
https://drive.google.com/file/d/1cqFRZsKhCfAXpJk9lj7U9K_OY4BT8mIm/view?usp=sharing

**Comment by Santienper** [comment]
Hemos solucionado el error.
