### ISSUE TITLE
Fallo en prueba de poder de traje 2

### ISSUE THREAD

**Issue by AndreaVegaSaugar** [Proyectos1-FDI-UCM/c2022-Grupo05#4]
##Fallo en prueba de poder de traje 2: 
Al usar el dash mejorado para atacar a un enemigo de 2 vidas, este no sufría daño/moría.
##Pasos 
Obtener mejora de traje.
Acercarse a un enemigo de 2 vidas y usar dash mejorado.
En vez de ser eliminado, el enemigo ignora por completo el efecto del ataque.
##Captura de pantalla o vídeo 
[](https://drive.google.com/file/d/1Ra05VeWowJta1unUWlUiPmqEz3tJB3uM/view?us p=sharing)

**Comment by Santienper** [comment]
El enemigo tiene 2 puntos de vida, por lo que un único dash mejorado no le mata, ya que este quita 1 punto de vida. Después de haber probado en el juego, hemos podido confirmar que sí hace daño.
