### ISSUE TITLE
Fallo prueba de gravedad

### ISSUE THREAD

**Issue by AndreaVegaSaugar** [Proyectos1-FDI-UCM/c2022-Grupo05#5]
Al saltar desde el techo con gravedad invertida sobre unos pinchos del suelo, mi gravedad se invertía al sufrir daño..
##Pasos 
Obtener piedra antigravedad.
Cambiar tu gravedad.
Acercarse a una zona con pinchos en el suelo .
Saltar sobre los pinchos, al hacerte daño, cambia la gravedad.
##Captura de pantalla o vídeo 
https://drive.google.com/file/d/1ZJqYpL98g0GTwqGO_pBe_ETqTvyu5B-9/view?usp=sharing

**Comment by Santienper** [comment]
Eso es intencionado (así no se genera un loop infinito de daño en otras zonas), hemos encontrado la manera de hacer que el cambio sea más rápido, para que se note más que lo es. Muchas gracias igualmente.
