### ISSUE TITLE
Fallo de cámara: 

### ISSUE THREAD

**Issue by AndreaVegaSaugar** [Proyectos1-FDI-UCM/c2022-Grupo05#6]
Al llegar a cierto punto del “segundo nivel”, la cámara se desplaza dejando atrás al personaje.
##Pasos 
Llegar a la zona indicada.
La cámara continúa su avance, dejando atrás al jugador.
##Captura de pantalla o vídeo 
https://drive.google.com/file/d/1zUpAzongxiny7Gh05zMcuy4aaQTvTLQx/view?usp=sharing

**Comment by MattCastUCM** [comment]
Problema arreglado.
