### ISSUE TITLE
Fallo de animación del enemigo: 

### ISSUE THREAD

**Issue by AndreaVegaSaugar** [Proyectos1-FDI-UCM/c2022-Grupo05#7]
La animación del enemigo atraviesa de forma intermitente los pinchos.
##Pasos 
Observar como el enemigo parece atravesar de forma intermitente unos pinchos.
##Captura de pantalla o vídeo 
https://drive.google.com/file/d/1u3DMnRpM-U_bhc9wm_0fnaabisG-kBgZ/view?usp=sharing

**Comment by MattCastUCM** [comment]
Arreglado.
