### ISSUE TITLE
Disparo atraviesa pared

### ISSUE THREAD

**Issue by f0reil** [Proyectos1-FDI-UCM/c2022-Grupo05#9]
### **Descripción**

El disparo atraviesa ciertas paredes, como columnas. Si el
jugador se queda apuntando a una se ve como el proyectil se refleja en el otro extremo, y en ocasiones puntuales atraviesa el muro. Era de esperarse que el proyectil chocase siempre con el extremo de la pared más cercano.

### **Pasos** 

1.  Ve a una de las paredes del juego. Una en la que se pueda ver el otro lado (una columna, por ejemplo).
2.  Dispara en su dirección varias veces, dejando pulsado el disparo para más comodidad.
3.  Muévete por el sitio, salta, hasta observar como el
proyectil se refleja en el otro lado e, incluso, lo atraviesa.

### **Captura de pantalla o vídeo**

https://drive.google.com/file/d/1PmywdXtzJxHE6fnqdHwoDR3pqgXtBjT7/view?usp=sharing

**Comment by likangwu03** [comment]
Error solucionado
